# Generated by Django 2.2.3 on 2019-07-08 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190629_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 17, 18, 323997, tzinfo=utc)),
        ),
    ]
