# Generated by Django 2.2.3 on 2019-07-10 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190708_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 17, 47, 3, 934619, tzinfo=utc)),
        ),
    ]
